### ISSUE TITLE
Failure to install K on a fresh Ubuntu Jammy machine (via Vagrant)

### ISSUE THREAD

**Issue by h0nzZik** [runtimeverification/kup#10]
Steps to reproduce:
1. connect to a fresh Ubuntu Jammy Vagrant machine
```sh
vagrant init ubuntu/jammy64
vagrant up
vagrant ssh
```

2. Install KUP (inside the ssh connection)
```sh
bash <(curl https://kframework.org/install)
```
3. Disconnect and connect again (`vagrant ssh`) to get a fresh shell

4. Try install K
```sh
kup install k
```
the output is:
```
[1/9/10 copied (1654.1/1654.1 MiB), 358.0 MiB DL] fetching source from https://cache.iog.io❗ The operation could not be completed. See above for the error output ...
```

**Comment by goodlyrottenapple** [comment]
hmm weird. I get the same error, but running `kup install k` succeeds the second time and seems to work ok

**Comment by ehildenb** [comment]
@h0nzZik can you confirm that this is still an issue on most recent `kup`? Also, can you confirm that rerunning it makes it work the second time?

**Comment by h0nzZik** [comment]
I cannot reproduce the steps on the `ubuntu/jammy64` Vagrant box, because it requires Virtualbox which is currently broken on my machine. However, I tried a different box - `generic/ubuntu2004`. I used the steps as before, but used
```
vagrant init generic/ubuntu2004
vagrant up --provider=libvirtd
```
instead, and `kup` seems to install `k` correctly.
I will try the `ubunt/jammy64` on another machine when I have the chance.

**Comment by geo2a** [comment]
I also tried to use `vagrant` to set up an isolated Ubuntu environment, and I can confirm that the original reproduction scenario by @h0nzZik still results in a similar problem:
```
kup install k
[1/15/16 copied (1828.7/1828.7 MiB), 114.3 MiB DL] fetching source from https://k-framework.cachix.org❗ The operation could not be completed. See above for the error output ...
```
I know that `vagrant` uses [passwordless `sudo`](https://stackoverflow.com/questions/30432408/why-can-user-vagrant-do-sudo-su-without-entering-password) --- perhaps it breaks some implicit assumptions `kup` or Nix make?

**Comment by goodlyrottenapple** [comment]
@geo2a can you:
a) provide the exact commands for seting up vargrant + vagrant version + host os
b) try running kup install k again and see if it still can't complete?

**Comment by goodlyrottenapple** [comment]
Upon investigation, this turns out to be a memory issue. Vagrant allocates too little memory to the VM by default and nix being as memory hungry as it is, simply uses all the memory until the OS kills it. I will open a PR with a more informative message when this happens...
