### ISSUE TITLE
`kup list` does not show locally installed versions of tools

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/kup#101]
If I do `kup install kontrol --version .` inside the `kontrol` repository, then do `kup list`, it shows `kontrol` as not installed. It should instead point to the path it was installed from, or the commit it was installed from, or `COMMIT-dirty` if the commit is dirty.

Discovered by several members of the Kontrol team.

**Comment by goodlyrottenapple** [comment]
completed in #102
