### ISSUE TITLE
`kup list PKG` to show which versions we already have local caches of

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/kup#17]
Is it possible to have `kup list PKG` display which versions I already haev in local cache? Maybe as another column, or as a color code (with a legend).

![image](https://user-images.githubusercontent.com/12721972/201262857-47a20b3d-a512-484b-ac37-c22e64277e87.png)

I know I've installed one of these in the past, and removed it (for testing something), but I have no idea which one. I'd like to reinstall it, doesn't matter which version, just want the one that's already cached.

**Comment by ehildenb** [comment]
So `kup clean` and `kup gc` would basically just be pre-filled Nix commands as well, but targeting our packages? I like that idea.

Is there any way we could just have a generic way to call any nix command with the arguments prefilled to filter for our needs?

**Comment by goodlyrottenapple** [comment]
This has been implemented for the binary cache now:

<img width="656" alt="image" src="https://github.com/runtimeverification/kup/assets/10553895/f7afa749-0e74-4354-8c6f-57ab4eba8683">
