### ISSUE TITLE
List new haskell backend on `kup`

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/kup#18]
This will require that `kup` support private repositories. Two paths towards that I can imagine are:

- Have the user set `GITHUB_TOKEN`, and if that's set then use it to fetch the data from GitHub.
- Have a private cache which you can opt into `kup private-cache ...` or something?

This also requires that new haskell backend is set up with a Nix flake.

**Comment by ehildenb** [comment]
Related https://github.com/runtimeverification/hs-backend-booster/issues/26

Possible close this one in favor of that one.

**Comment by goodlyrottenapple** [comment]
the booster can now be added given https://github.com/runtimeverification/kup/issues/30 has been merged
