### ISSUE TITLE
Private repositories and private caches

### ISSUE THREAD

**Issue by goodlyrottenapple** [runtimeverification/kup#30]
## Github auth

kup can already handle using github repositories with SSH access (due to issues with 2FA auth, will switch from using https+git to ssh+git in a future PR). This requires the user to have git with SSH set up on their machine. However, we could also enable access via github token, where instead of adding their ssh key to github, the user can instead generate a personal access token (https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) and use this to access the private repo. Is this something we want to support?

## Cache specification and auth

To make using private cache as seamless as possible, I suggest we do the following. Nix flakes have a way of specifying extra nix config; i.e. in our flake, we can write:

```nix
{
  description = "hs-backend-booster";
  inputs = ...;
  outputs = ...;

  nixConfig = {
    extra-substituters = [ "https://runtimeverification.cachix.org" ];
    extra-trusted-public-keys = [
      "runtimeverification.cachix.org-1:..."
    ];
  };
}
```

where `nixConfig` specifies the private cache and its public key that we want to use. This information is not sensitive and as such I don't think it would be a risk to include.

If we do use this route to specify the substituter, once we call `kup add`, we could read this data from the flake and test if a) the cache has already been added b) if not, whether it is private. If it is private, we could then prompt the user to provide an auth token for accessing the cache. This token would then be stored in a netrc file, the contents of which look like this:

```
machine runtimeverification.cachix.org password  <AUTH_TOKEN>
```

This is a standard config file used by curl, which nix (it seems?) uses when accessing the private cache and is the same mechanism cachix uses when adding a private substituter.

**Comment by ehildenb** [comment]
The one modification I would make to the plan is the storage to the `netrc` file. Is it possible to make the query using the GITHUB_TOKEN a single time, and then ask the user "would you like to make this permanent by writnig the GH token to ~/path/to/netrc/file"? That way, we aren't storing users GH tokens on disk without prompting them about it.

**Comment by goodlyrottenapple** [comment]
so the netrc file stores the cachix auth token not the github one. I haven't really though about the github auth token much, beyond potentially passing it initially via a flag, e.g. `kup add booster ... --github-auth-token ...`. We would then probably store it in `~/.config/kup/user_packages.ini`. We could prompt the user if they want to save it, but frankly i'm not sure it makes sense, given that it is necessary every time we call any of kup commands (except for `kup remove` i think)

**Comment by ehildenb** [comment]
So, I'm not fully understanding.

- GH token is used to retrieve the `flake.nix` the first time? But it's not needed except for that first time? Or it's needed every subsequent query?
- Cachix token is used to retrieve data from the private cache, and so likely needs to be stored on disk directly? How do other projects use private cachix caches? Does the `cachix` command provide a way to manage these?

**Comment by goodlyrottenapple** [comment]
The GH token would need to be used every time we fetch the flake, which is every time we check the version or do an install/update. Using a GH token is not necessary if you have SSH access set up for github.

Cachix stores the auth token in its own config file + writes the auth token into the netrc file for each individual cache. I suspect this is because you can store an admin auth token which can be used to log into multiple repos and the netrc file lists each of those logins separately.
