### ISSUE TITLE
Issues when using Nix to install K on M1 and M2 Macs 

### ISSUE THREAD

**Issue by reekamaharaj** [runtimeverification/kup#39]
Installing K on M1 and M2 Macs seems to be problematic when trying to use Nix. However not impossible. The following steps have worked for myself and another dev. See [Slack conversation](https://runtimeverification.slack.com/archives/C022YGTV4JK/p1675786821068639) 

1. Uninstall nix completely. See ([nix docs uninstall nix on mac](https://nixos.org/manual/nix/stable/installation/installing-binary.html) or [this article](https://iohk.zendesk.com/hc/en-us/articles/4415830650265-Uninstall-nix-on-MacOS) for steps).

2. In terminal run: `bash <(curl https://kframework.org/install)`
3. The above script has problems when it gets to ` . "$HOME"/.nix-profile/etc/profile.d/nix.sh` and returns an error related to making/backing up `/etc/bashrc`
4. After the error. I tried the Nix command and it said it wasn't found. So, I removed the Nix reference from `/etc/zshrc` and added it to the end of `./zshrc`
```
 # Nix
 if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
    . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
 fi
 # End Nix
```
5. Then restarted my terminal and ran the following:
`nix-shell -p nix-info --run "nix-info -m"`
`nix-env -iA nixpkgs.hello`
`nix profile install github:runtimeverification/kup#kup \\
  --option extra-substituters 'https://k-framework.cachix.org/' \\
  --option extra-trusted-public-keys 'k-framework.cachix.org-1:jeyMXB2h28gpNRjuVkehg+zLj62ma1RnyyopA/20yFE=' \\
  --experimental-features 'nix-command flakes'`
`kup install k`

6. There was some kind of response that told me to run the following:
`echo "trusted-users = root reekamaharaj" | sudo tee -a /etc/nix/nix.conf &&\
sudo pkill nix-daemon`
`sudo mkdir -p /etc/nix && sudo touch /etc/nix/nix.conf`
7. Then ran `kup install k` again
8. After it successfully completed I ran `kup list k` to check that it installed and got confirmation.

**Comment by goodlyrottenapple** [comment]
I have spun up a new VM and tried to install kup with similar results. Looks like on mac (M1 at leat, not tested intel), the nix installer should not call the following for it's setup:

```
. "$HOME"/.nix-profile/etc/profile.d/nix.sh
```

We should modify our script to only run the above if on a linux machine. The above command is used during the install of kup to bring nix into scope of the current terminal window. We will probably need to do a similar step, or else ask the user to close the terminal window, open a new one and re-run the kup install script, which obviously isn't the best user experience.

**Comment by Baltoli** [comment]
Some investigation possibly needed on what the best VM solution is for macOS / arm64.
* Parallels
* Anka - still have a license but _not_ for CI, would work locally to spin up VMs.

**Comment by Baltoli** [comment]
@ehildenb @F-WRunTime is this mac in the colorado office, or somewhere else?
