### ISSUE TITLE
Failure to override pyk when installing KEVM

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/kup#43]
I'm trying to install KEVM with an overridden pyk, and it fails for some reason. Then the failure instructs me to add option `--show-trace`, which also fails:

![image](https://user-images.githubusercontent.com/12721972/221105306-87fb4eb9-6ab4-4448-9425-cd9d0e842618.png)

**Comment by goodlyrottenapple** [comment]
@ehildenb this has been fixed in the pyk repo by https://github.com/runtimeverification/pyk/pull/224. please merge master into any branches you wish to use as an override and the install should work again.
