### ISSUE TITLE
Warning on `kup shell k`

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/kup#63]
Not sure what package / dependency this refers to, but I get a (seemingly harmless) warning when running a `kup shell`:

```console
$ kup shell k
trace: WARNING: 9.2.7 is out of date, consider using 9.2.8.
```

**Comment by goodlyrottenapple** [comment]
this is a haskell.nix warning about the version of ghc from either the haskell or booster backend.... should disappear soon as we have migrated both repos to ghc 9.2.8

**Comment by goodlyrottenapple** [comment]
as this is emitted by nix which we have no control over, i will close
