### ISSUE TITLE
List KAVM

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/kup#7]
`kup` should handle [KAVM](https://github.com/runtimeverification/avm-semantics/):

- [x] Nix flake for KAVM.
- [x] Nix CI for KAVM.
- [x] Add templated files (no need to be perfect) to [our cookiecutter template](https://github.com/runtimeverification/python-project-template).
- [x] List KAVM here.

**Comment by goodlyrottenapple** [comment]
added nix flake + CI in: https://github.com/runtimeverification/avm-semantics/pull/165 and https://github.com/runtimeverification/avm-semantics/pull/166
added template files in: https://github.com/runtimeverification/python-project-template/pull/7
added kavm to kup: https://github.com/runtimeverification/kup/pull/9
