### ISSUE TITLE
`kup` installs an incompatible version of K

### ISSUE THREAD

**Issue by fiedlr** [runtimeverification/kup#82]
I ran the following on Ubuntu 22.04 with glibc 2.35:

```sh
kup install k --version v6.0.87
```

Everything worked, but when working with `pyk`, this led to the following `glibc` error: (see discussion https://runtimeverification.slack.com/archives/C042X4L8WVB/p1697738662981559 for more details)
```
E   ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by /tmp/tmpz3ekua7w/_kllvm.cpython-310-x86_64-linux-gnu.so)
```

After upgrading to Ubuntu 23.04 with a newer glibc, I am no longer getting the error. 

The point is that it seems that `kup` installed this K version despite its incompatibility with my system.

**Comment by Baltoli** [comment]
Do you have a minimal example for reproducing this with Pyk?

**Comment by goodlyrottenapple** [comment]
Yes, a reproduction would be helpful. For context, Nix installs its own glibc and links against it in all kup installed tools so this is likely an incompatibility between kup installed k and local checkout of pyk using poetry.

**Comment by fiedlr** [comment]
Unfortunately, I cannot easily reproduce any longer with the new system. But I just ran `make test-system` in our `proof-checker` repo on the `main` branch, which runs the integration suite that has not changed yet. I guess I could pinpoint the commit on which I ran it, would that help?

**Comment by goodlyrottenapple** [comment]
Hmm this is tricky, I don't think it's got anything to do with the commit of the repo. Not sure we can do much here unless someone else runs into this issue. As I mentioned, kup ships k with its own glibc so there is definitely potential for clashes with system installed glibc. From the error message above, it seems that the python bindings to the llvm backend were maybe compiled with a different gcc+glibc than stuff in k? @Baltoli does this sound right? I'm not entirely sure how the process of building the python bindings works in pyk.

**Comment by Baltoli** [comment]
That basically sounds plausible; I'll take a look at reproducing but this kind of thing can be quite tricky to nail down unfortunately

**Comment by Baltoli** [comment]
We resolved this issue in https://github.com/runtimeverification/kup/issues/92; the problem is that running:
```
poetry env use `which python3.10`
```
will point poetry to some non-Nix Python interpreter, which might be using a different version of glibc from Nixpkgs. In this case, by _coincidence_, upgrading Ubuntu fixed things, but that's not guaranteed.

The actual fix is to use:
```
poetry env use --no-cache $(k-which-python)
```
for development.
